---
- name: Create Wireguard client configuration file
  tags: configuration
  ansible.builtin.template:
    src: templates/wg-peer.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  when: inventory_hostname in groups["wgpeers"]

- name: Add ip address of Wireguard server to /etc/hosts
  tags: configuration
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ servername }}"
    line: "{{ serverip }}\t{{ servername }}"
    owner: root
    group: root
    mode: '0644'
  vars:
    servername: "{{ groups['wgserver'][0] }}"
    serverip: "{{ hostvars[servername]['ansible_facts']['default_ipv4']['address'] }}"
  when: inventory_hostname in groups["wgpeers"]
